Lock RbVmomi to 2.3.0 to fix Refresh errors
The newer RbVmomi 2.4.0 with vSphere 7.0 support causes errors when
refreshing a vCenter:
`[NoMethodError]: undefined method `split' for #<RbVmomi::VIM::PhysicalNic:0x000000001154aba8>`

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1823192